### ISSUE TITLE
Chaning the bolor color of a shape 

### ISSUE THREAD

**Issue by MbProg** [mdaines/viz.js#101]
I have the simple following DOT script:
```
digraph G {
	subgraph cluster_1 {
		color=red;
		node [style=filled, color=grey,];
		b0 -> b1 ;
		label = "process #2";
	}
	start -> b0;
	start [shape=Mdiamond];
}
```
I just want to change the border color of `b1`, but I couldn't find out how to do that. How can I change the border color of `b1`?

**Comment by mattboehm** [comment]
You'd be better off asking this in a graphviz forum/mailing list or on stackoverflow, but anyway:

Before `b0 -> b1;` have a line that says `b1[color=red];` This defines the node and sets attributes specific to it.

**Comment by MbProg** [comment]
This doesn't change the **border color** but the area of the shape. But I got it, you have to use it in combination with `fillcolor`:
`[color=red, fillcolor=grey]`
