### ISSUE TITLE
Add CLI support so this can be run without a wrapper script

### ISSUE THREAD

**Issue by JakeSummers** [mdaines/viz.js#103]
Good Evening!

I am currently using this tool as part of my build pipeline to generate documentation for my project.  

Currently I need to use a wrapper script to get this running.  I invoke the wrapper script like this: `cat myDotFile.dot | node myWrapper.js > out.svg`.  

This is what the wrapper script looks like: 

```
const Viz = require('viz.js');

let data = '';

process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('data', function (chunk) {
    data += chunk;
});

process.stdin.on('end', function () {
    const result = Viz(data);
    console.log(result);
});

```

Would it be possible to make this directly invokable so that I could do something like:

```
node_modules/viz.js/vix.js --input myDotFile.dot --output myDotFile.svg
```

This would be awesome.  

Thanks !

**Comment by mdaines** [comment]
@JakeSummers Why do you want to use Viz.js and not the "real" `dot` program?

**Comment by JakeSummers** [comment]
Hi @mdaines ,

I want build dot diagrams as part of my build process but my build process needs to be OS independent.  Using this NPM package to build the dot files achieves that.

**Comment by mdaines** [comment]
Fair enough. However, I don't want to include a wrapper script in this project. You are of course free to publish your wrapper script as a separate NPM package that depends on Viz.js.

**Comment by JakeSummers** [comment]
Thanks for the consideration.
