### ISSUE TITLE
is it possible to add a link to some nodes?

### ISSUE THREAD

**Issue by Jiangshan00001** [mdaines/viz.js#109]
i would like to add a link to some node, if user click the node, will open the link.
is that possible?
howtodo?

**Comment by magjac** [comment]
Use the Graphviz [URL](https://www.graphviz.org/doc/info/attrs.html#d:URL) attribute on the node.

**Comment by mdaines** [comment]
Quick example:

```dot
digraph {
	a[URL="http://viz-js.com"]
}
```
