### ISSUE TITLE
The new TypeScript declaration breaks my build

### ISSUE THREAD

**Issue by maccesch** [mdaines/viz.js#115]
I used to use Viz.js 1.8.0 like this:
```typescript
import Viz from 'viz.js';
```
which worked just fine and is in tune like I use every other lib in this large sized project. But now I can't do that anymore.

It is especially important for me to use it that way because I actually only need it during development. So together with other dev-only code, I can simply include it in

```typescript
/// #if DEBUG
...
/// #endif
```

together with the ifdef-loader (webpack) to strip that code away in production.

**Comment by mdaines** [comment]
@maccesch, can you provide more context for this issue? I assume you are using webpack? How does your build break? What error are you seeing?

**Comment by maccesch** [comment]
@mdaines Thanks for the fast reply.

Yes, I'm using Webpack.
When I use the latest version it tells me at build time:

 ```
ERROR in [at-loader] ./some/path/CytoscapeDotLayout.ts:1:17 
    TS2306: File '/project/path/node_modules/viz.js/index.d.ts' is not a module.
```

My tsconfig.json:

```javascript
{
  "compilerOptions": {
    "lib": [
      "dom",
      "es5",
      "es2015",
      "es2015.promise"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
  }
}

```

**Comment by mdaines** [comment]
The TypeScript declaration file for v1.8.1 says that `Viz` is a global. I believe you can write just this for the import instead and the declarations will still work:

```typescript
import 'viz.js';
```

However, Viz.js does check for module.exports and use it if possible, so I will add that to the declaration.

**Comment by mdaines** [comment]
Hm, according to [this declaration template](http://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) you'll need to change your import either way?

```typescript
/*~ Note that ES6 modules cannot directly export callable functions.
 *~ This file should be imported using the CommonJS-style:
 *~   import x = require('someLibrary');
 *~
 *~ Refer to the documentation to understand common
 *~ workarounds for this limitation of ES6 modules.
 */
```

**Comment by maccesch** [comment]
It works indeed with just 

```typescript
import 'viz.js';
```

Thanks!
