### ISSUE TITLE
Document supported node shapes

### ISSUE THREAD

**Issue by NebuPookins** [mdaines/viz.js#122]
I tried to make a graph with nodes `node[shape="record", style=filled,fillcolor=gray95];` which did not appear to work mainly due to this implementation not recognizing the `record` shape. It'd be nice to have a list of the supported shapes. Based on https://github.com/mdaines/viz.js/blob/1b2d0ba32e163941fdd70302dea9f60e016f21b6/test-browser/graphs/shapes.dot it looks like it supports circle, egg, triangle, diamond and trapezium, but this is surely not a exhaustive list, as it doesn't mention `rectangle` which does appear to be supported.

**Comment by mdaines** [comment]
All of the Graphviz shapes should be supported, with the exception of user-defined shapes in some cases. Can you post an example?

I get the same output on http://viz-js.com for the following graph as I get using the `dot` program.

```dot
digraph structs {
   node[shape="record", style=filled,fillcolor=gray95];
   
   a[label="<f1>a|<f2>b"];
   b[label="<f1>x|<f2>y"];
   
   a:f1 -> b:f2;
}
```

**Comment by NebuPookins** [comment]
Thanks, it looks like your plugin does support records, but my graph is failing to render for a different reason.

This fails to render with `Error: lost 4 3 edge`:

```dot
digraph hierarchy {
node[shape=record,style=filled,fillcolor=gray95];
edge[dir=back, arrowtail=empty];

2[label = "{AbstractSuffixTree|+ text\n+ root|...}"];
3[label = "{SimpleSuffixTree|...| + constructTree()\l...}"];
4[label = "{CompactSuffixTree|...| + compactNodes()\l...}"];
5[label = "{SuffixTreeNode|...|+ addSuffix(...)\l...}"];
6[label = "{SuffixTreeEdge|...|+ compactLabel(...)\l...}"];

2->3;
2->4;
5->5[constraint=false, arrowtail=odiamond];
4->3[constraint=false, arrowtail=odiamond];
2->5[constraint=false, arrowtail=odiamond];
5->6[arrowtail=odiamond];

}
```

But this renders correctly:

```dot
digraph hierarchy {
node[style=filled,fillcolor=gray95];
edge[dir=back, arrowtail=empty];

2[label = "{AbstractSuffixTree|+ text\n+ root|...}"];
3[label = "{SimpleSuffixTree|...| + constructTree()\l...}"];
4[label = "{CompactSuffixTree|...| + compactNodes()\l...}"];
5[label = "{SuffixTreeNode|...|+ addSuffix(...)\l...}"];
6[label = "{SuffixTreeEdge|...|+ compactLabel(...)\l...}"];

2->3;
2->4;
5->5[constraint=false, arrowtail=odiamond];
4->3[constraint=false, arrowtail=odiamond];
2->5[constraint=false, arrowtail=odiamond];
5->6[arrowtail=odiamond];

}
```

The only difference between the two is I omitted the `shape=record`, so I had incorrectly concluded this meant that record shapes were not supported.

**Comment by NebuPookins** [comment]
It looks like the issue is related to some interaction between the dot engine and the constraint attributes.

This renders in the dot engine:

```dot
digraph hierarchy {
node[shape="record",style=filled,fillcolor=gray95];
edge[dir=back, arrowtail=empty];

2[label = "{AbstractSuffixTree|+ text\n+ root|...}"];
3[label = "{SimpleSuffixTree|...| + constructTree()\l...}"];
4[label = "{CompactSuffixTree|...| + compactNodes()\l...}"];
5[label = "{SuffixTreeNode|...|+ addSuffix(...)\l...}"];
6[label = "{SuffixTreeEdge|...|+ compactLabel(...)\l...}"];

2->3;
2->4;
5->5[constraint=false, arrowtail=odiamond];
4->3[arrowtail=odiamond]; //Removed constraint attribute
2->5[arrowtail=odiamond]; //Removed constraint attribute
5->6[arrowtail=odiamond];
}
```

And the original graph also renders if I change the engine to anything other than dot, for example circo.

**Comment by mdaines** [comment]
The Graphviz command-line program produces output for that first graph, but also produces errors (and exits with an error code). The output for that graph is incorrect -- it omits edges as the error message implies.

Viz.js always throws an error if Graphviz produces one, so I believe that's why you're seeing that in this case. I think it might make sense to do something different from the current behavior, but I'm not sure what. I've opened #123 to track this.
