### ISSUE TITLE
html label cannot render the online image

### ISSUE THREAD

**Issue by yuanqingfei** [mdaines/viz.js#125]
I tried to render 
```js
digraph {
    //splines = ortho;
    //rankdir="LR";
    node [shape = box, color=blue];
    edge [dir = none];

I0000 [label=<<table border="0" cellborder="0"><tr><td><img src="http://yuanqingfei.me/images/sparrow2.jpeg"/></td></tr><tr><td>清<br/>袁<br/>1122</td></tr></table>>]
}
```

in http://viz-js.com/  . It doesn't work unless I remove the 'img' element. But in offline graphviz, it works. Anything I missing? or this is a bug?

**Comment by mdaines** [comment]
While you can use the image attribute with Viz.js (even HTTP URLs), viz-js.com doesn't support this, since it currently has no way of loading images to determine their dimensions. `<img>` tags should work, but I haven't tested them.

When using images with Viz.js you'll need to specify the dimensions of the image:

```js
Viz("digraph { ... }", {
  images: [
    { href: "http://example.com/test.png", width: "400px", height: "300px" }
  ]
});
```

**Comment by yuanqingfei** [comment]
I just tried. It still doesn't work in http://viz-js.com even I add dimensions to my img element. I really hope that it can work properly with 
```html
<img src="http://yuanqingfei.me/images/sparrow2.jpeg" width="50" height="60"/>
```

**Comment by mdaines** [comment]
Sorry, viz-js.com doesn't support that. And I believe Graphviz doesn't support width and height attribute on `<img>` elements, but I could be wrong.

Images are only supported using the `images` option when using Viz.js as a library.

It would be nice to be able to use images in the web UI, so I've added an issue for that: #126
