### ISSUE TITLE
Viz.js 2.0 should work in Observable

### ISSUE THREAD

**Issue by mdaines** [mdaines/viz.js#131]
So far, two issues with this:

- It appears that Observable would already run Viz.js in a worker, and creating a worker with an unpkg.com URL fails in that context.
- `full.js.opaque` isn't served with a script MIME type, so even if we want to just use the `Module` and `render` options directly, we can't.

The easiest solution would appear to be abandoning the odd `.js.opaque` file name extensions.

In Chrome, this fails `SecurityError: Failed to construct 'Worker': Script at 'https://unpkg.com/viz.js@2.0.0-pre.7/full.js.opaque' cannot be accessed from origin 'https://anonymous.static.observableusercontent.com'.`

```js
{
  let deps = Promise.all([
    require("viz.js@2.0.0-pre.7"),
    resolve("viz.js@2.0.0-pre.7/full.js.opaque")
  ]);
  
  return deps.then(([Viz, workerURL]) => {
    return new Viz({ worker: workerURL }).renderString('digraph { a -> b }');
  });
}
```

In Chrome, this fails with `Error: unable to load module`. On the console, the error is `Refused to execute script from 'https://unpkg.com/viz.js@2.0.0-pre.7/full.js.opaque' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

```js
{
  let deps = Promise.all([
    require("viz.js@2.0.0-pre.7"),
    require("viz.js@2.0.0-pre.7/full.js.opaque")
  ]);
  
  return deps.then(([Viz, options]) => {
    return new Viz(options).renderString('digraph { a -> b }');
  });
}
```

**Comment by mdaines** [comment]
The following works now:

```js
{
  const deps = Promise.all([
    require("viz.js@2.0.0-pre.8"),
    require("viz.js@2.0.0-pre.8/full.render.js")
  ]);
  
  return deps.then(([Viz, options]) => {
    return new Viz(options).renderString('digraph { a -> b }');
  })
  .then(string => {
    const fragment = html([string]);
    const svg = fragment.removeChild(fragment.firstElementChild);
    return svg;
  });
}
```

**Comment by mdaines** [comment]
The rendering script file can also be used directly:

```
{
  const src = 'digraph { a -> b }';

  return require("viz.js@2.0.0-pre.8/full.render.js")
  .then(({ Module, render }) => {
    const instance = Module();
    const string = render(instance, src, { files: [], format: 'svg', engine: 'dot' });
    const fragment = html([string]);
    const svg = fragment.removeChild(fragment.firstElementChild);
    return svg;
  });
}
```

**Comment by mbostock** [comment]
Here’s a working notebook:

https://beta.observablehq.com/@mbostock/hello-viz-js

I’ve also updated [@observablehq/graphviz](https://github.com/observablehq/graphviz) to use Viz.js 2.0 (in-process, not in a web worker), as shown here:

https://beta.observablehq.com/@mbostock/graphviz
