### ISSUE TITLE
ES Module Support

### ISSUE THREAD

**Issue by nikeee** [mdaines/viz.js#132]
Is there any plan to support ES modules?
[Firefox 60 is just around te corner](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/) and supports ES Modules. From there on, all major browsers support ES Modules.

Edit: Or a I missing something and Viz.js already suports ES modules? If so, you can close this issue.

How would one include the es module? Like this?
```HTML
<script type="module" src="viz.es.js"></script>
```

**Comment by mdaines** [comment]
The prerelease versions of Viz.js support this as of 2.0.0-pre.7. Here's an example:

https://github.com/mdaines/viz-examples/blob/master/script-tag/module.html
