### ISSUE TITLE
HTML-like labels do not render properly in v1.8.0+

### ISSUE THREAD

**Issue by hjkatz** [mdaines/viz.js#137]
The following dot renders correctly on the example site with version 1.7.0:

```
digraph "example" {
  rankdir=LR;
  ranksep=4;
    "my_node" [shape=record
    label=<
      <table border="0" cellborder="0">
        <tr>
          <td>
            <b><font face="courier" point-size="16">my_node</font></b>
          </td>
        </tr>
      <tr>
          <td align="left">
            <font face="courier" point-size="14">sub_value</font>
          </td>
        </tr>
        </table>
      >]
}
```

In versions starting with 1.8 (including 2.0) the rendered svg does not include the sub_value element.

I'm not sure what's going on, but I'm using v1.7.0 for the time being.

**Comment by magjac** [comment]
It renders on http://viz-js.com/.

However, you should use shape=plain with [HTML-like labels](https://www.graphviz.org/doc/info/shapes.html#html). If you do, it will respect border="0" and not draw the border.

**Comment by hjkatz** [comment]
@magjac I agree with you, that's what I meant by saying it renders on the example site. However, http://viz-js.com/ is currently using version viz.js@1.7.2, not the latest, and this is why I've dropped my version for the time being.

**Comment by mdaines** [comment]
@hjkatz Can you attach an image of the expected output? This is what I get using Viz.js 2.0.0:

![unknown](https://user-images.githubusercontent.com/1383/40491814-0e8a74ee-5f3d-11e8-9fb0-805ea4a49def.png)

For ease of testing, there is a new version of the web UI that does use 2.0.0 here: https://mdaines.github.io/viz-ui/ I plan to update viz-js.com soon.

**Comment by hjkatz** [comment]
@mdaines I found the problem. I was using `lite.render.js` not `full.render.js`. I'm not sure why this would be the issue though, because I'm only using SVG and the DOT engine so I assumed lite would work fine.

Feel free to close this issue.

**Comment by mdaines** [comment]
@hjkatz Ah, I see. The "lite" version doesn't support HTML labels as it omits the Expat XML parser.
