### ISSUE TITLE
gh_pages: Features for viz-js.com

### ISSUE THREAD

**Issue by dnephin** [mdaines/viz.js#138]
Hello, couple questions

I noticed you recently released a 2.0 version of the library. I'm wondering if you are planning on updating viz-js to use the new version.

I've been working on some changes to the UI for my own use (https://dnephin.github.io/viz-dot-editor/) and I'm wondering if you would be interested in a PR for any of these:

Features:
* 1e667a948e8c29b29ba03fcb20d07ec38752a0f1 save the current editor contents in localStorage so they are available again if the browser is closed before work is saved.
* b389aeb633886f8eb345bbf40d3a18c3cd8e26e0, b389aeb633886f8eb345bbf40d3a18c3cd8e26e0 add a button to download the `dot` source and formatted output

Other changes are to CSS, adding icons, and some developer tools for running `browser-sync` in a container.

**Comment by mdaines** [comment]
@dnephin I recently rewrote the web UI for Viz.js using React (that's the viz-ui project). It's still missing a few features from the current viz-js.com, and I have been wondering whether or not to reimplement them.

Going forward I think I am going to stick with adding as little as possible -- I don't want it to be much beyond a basic demo. But I definitely encourage you to develop your own editor. It would be nice to see something like jsfiddle for DOT, or something that could work with gists.
