### ISSUE TITLE
Support for async iterators

### ISSUE THREAD

**Issue by aduh95** [mdaines/viz.js#140]
This is a feature request.

It would be nice if `viz.js` would support [async] iterator like objects (array, Stream, generators, async generators, ...) since the API is `async` anyway. Here is an idea of what I have in mind:

```js
Viz.prototype.renderIterator = async function (iterator , { format = 'svg', engine = 'dot', files = [], images = [], yInvert = false } = {}) {
    for (const image of images) {
      files.push({
        path: image.path,
        data: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="${image.width}" height="${image.height}"></svg>`
      });
    }
    this.wrapper.initRendering({ format, engine, files, images, yInvert });

    for await (const chunk of iterator) this.wrapper.push(chunk);

    return this.wrapper.getRendered();
})
```

The goal of this is to make file rendering more efficient and less memory consuming:

```js
/* On the browser */
fetch("/path/to/file.dot").then(response=>{
  if (response.ok) {
    // no need to fill a buffer in the memory
    return viz.renderIterator(response.body);
  }
}).then(svgString => {/* SVG is rendered */});

/* On Node */
viz.renderIterator(fs.createReadStream("/path/to/file.dot"))
    .then(svgString => {/* SVG is rendered */});
```

Because I am not familiar on how the I am not sure it makes sense on a performance perspective. Can the Graphviz algorithm start rendering even if it does not have the full document? If so, is there an easy way to implement a method that allow to take advantage of that?
I just wanted to throw this idea I had in mind, I know `DOT` files are probably never big enough for memory buffering to be a serious issue.

Also, `renderIterator` kind of sucks as a name, it does not quite explain what it is doing, I am sure we can do better.

**Comment by mdaines** [comment]
Right now I consider the work done by the render functions to be indivisible. It might be possible to break it up in some way, though.

You can use something like tiny-worker in Node to approximate using web workers in the browser. This is adapted from the tests:

```js
const Viz = require('viz.js');
const Worker = require('tiny-worker');

let worker = new Worker('viz.js/full.render.js');
let viz = new Viz({ worker });
  
return viz.renderString('digraph { a -> b; }')
.then(function(result) {
  console.log(result);
  worker.terminate();
});
```
