### ISSUE TITLE
Render as PNG and SVG file in API 2.0

### ISSUE THREAD

**Issue by nikeee** [mdaines/viz.js#141]
The API docs do not mention anything that can render a graph to a PNG or SVG file. It was possible in `1.x`, but now it seems to be gone.

Is this planned for the future? This would be a very nice feature!

**Comment by nikeee** [comment]
Looking at the source, there are several references to a `png` format. Using `renderImageElement`, it seems to be possible to render an [`Image`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image). My intention was to let the user download the image.

Since the `HTMLImageElement` has a `src` property, which can be used to download the PNG image, this seems to work for me.

All in all, this issue seemed invalid to me.

**Comment by mdaines** [comment]
Yes, the `renderImageElement` function in 2.x is the equivalent of the "png-image-element" format in 1.x.
