### ISSUE TITLE
Add option to remove svg prolog from generated string

### ISSUE THREAD

**Issue by christianvoigt** [mdaines/viz.js#146]
Hi, I am still using viz.js in the old synchronous mode (using `Viz(dotString)`) and it seems that you recently added a svg prolog to the result: `<?xml version="1.0" encoding="UTF-8" standalone="no"?> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`. 

In an older version there were only comments used, right? Currently I can not use the asynchronous methods, but I still need to insert the svg into the DOM without the prolog. As far as I can see, I have to replace the prolog myself using Regex, but it would be nice if I could avoid that. 

Could you add an option so that it is possible to remove it?

**Comment by aduh95** [comment]
Couldn't you use [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) for that purpose?

```js
function getSVGNode(svgString) {
  return new DOMParser().parseFromString(svgString, 'image/svg+xml').documentElement;
}

var svg = getSVGNode(stringFromViz);
// Get the string with the outerHTML property
console.log("SVG string", svg.outerHTML);
// Append the node to the DOM
document.body.appendChild(svg):
```

**Comment by christianvoigt** [comment]
Thank you for the tip, but the code has to run in node.js so I can not use DomParser.

**Comment by mdaines** [comment]
I’m not aware of an option to remove the prolog—Viz.js doesn’t add it, so perhaps it was added to Graphviz output at some point? Unless there is an option I can pass to the Graphviz library to remove it, I would probably need to resort to a regular expression or parsing the SVG as well.

**Comment by aduh95** [comment]
Take a look at [SVGO](https://github.com/svg/svgo) which will remove the prolog, DOCTYPE and produce a much smaller string without the need to hard code a dirty regex yourself that could break if Graphviz changes its output in a future version.

**Comment by christianvoigt** [comment]
@mdaines: Ah ok, that makes sense. I thought this was coming from viz.js

@aduh95: SVGO looks great, though I am also hesitant to add another dependency (the code will run in node and the browser so file size should be kept small). So I will have to think about it.
