### ISSUE TITLE
Nodejs and Graphviz

### ISSUE THREAD

**Issue by saraa1986** [mdaines/viz.js#149]
Hey.
I would like to use graphviz package in my Nodejs project.  I want to have neat graph to represent the idea of my work; For which I would like to have a graph like [this](https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.html), with sub-graphs. I have already install the graphviz package in my nodejs project by which I can drew simple graph, following this [code ](https://github.com/glejeune/node-graphviz).but I cannot have sub-graphs. I appriciate if someone can point me to a document where they explain how to use Graphviz in Nodejs.

**Comment by aduh95** [comment]
Did you take a look at the [Usage page]{https://github.com/mdaines/viz.js/wiki/Usage#as-a-commonjs-module-such-as-in-nodejs} in the wiki? Is there a point you'd like to be clarified?

**Comment by saraa1986** [comment]
hi @aduh95 . Thanks for the link. Can you advise me on how can I have the output in a vsiual format like png or svg.

**Comment by aduh95** [comment]
Well, by default `viz.js` outputs an SVG, and you can change that passing a [`RenderOption`](https://github.com/mdaines/viz.js/wiki/API#render-options) object as second argument of the `renderString` method.

Here is an example taken from the wiki using the graph you linked to on the Graphviz docs:

```js
const Viz = require('viz.js');
const { Module, render } = require('viz.js/full.render.js');

const grpah = `
digraph G {
	subgraph cluster_0 {
		style=filled;
		color=lightgrey;
		node [style=filled,color=white];
		a0 -> a1 -> a2 -> a3;
		label = "process #1";
	}

	subgraph cluster_1 {
		node [style=filled];
		b0 -> b1 -> b2 -> b3;
		label = "process #2";
		color=blue
	}
	start -> a0;
	start -> b0;
	a1 -> b3;
	b2 -> a3;
	a3 -> a0;
	a3 -> end;
	b3 -> end;

	start [shape=Mdiamond];
	end [shape=Msquare];
}`;

// this is default, passing an empty object gives the same result
const renderOptions = { format:"svg" };

let viz = new Viz({ Module, render });

viz.renderString(graph, renderOptions)
  .then(result => {
    console.log(result);
  })
  .catch(error => {
    // Create a new Viz instance (@see Caveats page for more info)
    viz = new Viz({ Module, render });

    // Possibly display the error
    console.error(error);
  });
```

Running this script on Node returns a SVG similar to the one on the Graphviz docs.

![Graphviz example](https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.png)

Maybe you should explain more what you are trying to achieve, what you expect and you are actually getting. Linking to your repo doesn't really help, you need to provide a simple script to reproduce and explain what bothers /  confuses you in the current behavior.

**Comment by saraa1986** [comment]
this is exactly what I want. to have a graph like that. Where the SVG file will be saved? How can I specify the path? I have tried the followig:

**Comment by aduh95** [comment]
As its name suggests, `renderString` renders a string. The string represents the graph on the format specified in the `RenderOptions` object. Once the Promise is resolved, you can do whatever you want with that string. In my example, I pass it to `console.log`. If you run the script I put in my previous comment, the SVG will be written on stdout.

```bash
node ./test_subgraphs.js > subgraphs.svg
```

However, if you want to save it programmatically on a file, take a look on the [File System](https://nodejs.org/docs/latest-v10.x/api/fs.html) docs of Node.js, this is not a `viz.js` issue. Here is an example of a function you can build:

```js
const fs = require("fs");
const util = require("util");
const writeFile = util.promisify(fs.writeFile);

const Viz = require("viz.js");
const { Module, render } = require("viz.js/full.render.js");
let viz = new Viz({ Module, render });

/**
 * Generates a graph and saves it to a file
 * @param {string} graph
 * @param {string} filePath
 * @returns {Promise<void>}
 */
const saveGraphToFile = (graph, filePath) =>
  viz
    .renderString(graph)
    .then(svgString => writeFile(filePath, svgString))
    .catch(error => {
      viz = new Viz({ Module, render });

      // Possibly display the error
      console.error(error);
    });
```

**Comment by saraa1986** [comment]
@aduh95  You really helped me. Thanks :) 👍

**Comment by aduh95** [comment]
You're welcome. Could you please this issue if you solved your problem?
