### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by FliegendeWurst** [mdaines/viz.js#152]
make deps log: https://pastebin.com/TQtbJg5R (probably fine)
make all log: https://pastebin.com/vE9HMiDk ("cannot find library", "unresolved symbol")

I'm using Opensuse Tumbleweed.

**Comment by mdaines** [comment]
This could be the problem? (in the `make deps` output)

```
Libraries have been installed in:
   /tmp/viz.js/prefix-full/lib64
```

On my system, the libraries are "installed" in `prefix-full/lib`.
