### ISSUE TITLE
Will typings ever come back?

### ISSUE THREAD

**Issue by SaphuA** [mdaines/viz.js#155]
I was so happy when viz finally supported typings and now they are removed without any justification as to why. Is this temporary or will they never come back?

**Comment by mdaines** [comment]
I don't have time to maintain them. Part of that is that I don't use TypeScript, so it's more effort to ensure that the type information is correct.

**Comment by SaphuA** [comment]
It's not that much trouble to add typings since the library isn't that complex. I just did it for the methods that we use. Any chance they get added back in if I type the entire library?

```
declare module 'viz.js' {
    class Viz {
        constructor();
        renderString(src: string, options?: Options): Promise<string>;
        renderSVGElement(src: string, options?: Options): Promise<SVGSVGElement>;
    }

    class Options {
        engine?: "circo" | "dot" | "fdp" | "neato" | "osage" | "twopi";
        format?: "svg" | "dot" | "xdot" | "plain" | "plain-ext" | "ps" | "ps2" | "json" | "json0";
    }

    export = Viz;
}
```

**Comment by IvanGoncharov** [comment]
@SaphuA You can submit your typings to DefinetlyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package
IMHO, it's the best option for a case when library author don't have time to maintain it.
