### ISSUE TITLE
Can't use ampersand (&) in URL

### ISSUE THREAD

**Issue by pokrakam** [mdaines/viz.js#157]
Viz.js throws an error if a URL has an ampersand in it.
Working example: 
`digraph G { 1; 2; 3 [URL="./?foo=1"] }`

Try adding another URL parameter: 
`digraph G { 1; 2; 3 [URL="./?foo=1&bar=2"] }`
And it comes up with an error:
![image](https://user-images.githubusercontent.com/25539927/48234443-84b57080-e3b1-11e8-9d4b-a897e887e8d2.png)
This fails with Safari on Mac and Chrome on Windows. I have also tried escaping it or adding another ampersand, no joy. 
It works fine with Graphviz 2.38 on Windows, example 2 above renders all three nodes.

**Comment by mdaines** [comment]
Escaping the ampersand works for me:

```dot
digraph G { 1; 2; 3 [URL="./?foo=1&amp;bar=2"] }
```

I believe the behavior of Viz.js is consistent with the regular version of Graphviz, because I see the same error when I ask the `dot` program to render that graph as SVG and look at it in a web browser.

**Comment by pokrakam** [comment]
Hi, thanks for looking into this! 
It's obvious now, and the error message makes sense too. I used regex escape "\"... 
It did work with straight ampersands with an earlier version - not sure which one, it was from 2017.
