### ISSUE TITLE
Question: how to display labels with quotation marks?

### ISSUE THREAD

**Issue by avet-dvlp** [mdaines/viz.js#158]
I am trying to display a graph where some labels have quotation marks inside.
But the code I am using is throwing an error:
```
var graph3 = 'strict digraph {"a a"->"bbb \"ccc"}';
var viz=new Viz();

viz.renderSVGElement(graph3)
  .then(function(element) {
    document.body.appendChild(element);
  })
  .catch(error => {
    // Create a new Viz instance (@see Caveats page for more info)
    viz = new Viz();

    // Possibly display the error
    console.error(error);
  });
```

At the same time I can see that http://viz-js.com/ displays it correctly. Any advice on how to encode the graph string correctly?

Thanks.

**Comment by mdaines** [comment]
You may need to escape both the backslash and the double quote within the label when writing the string in JacaScript, so that Graphviz will see a backslash and a double quote rather than just a double quote. Like this: `\\\"`

**Comment by avet-dvlp** [comment]
Nice, thanks a lot!
It works.
