### ISSUE TITLE
full.render.js is broken on Realese 2.1.1

### ISSUE THREAD

**Issue by zetaraku** [mdaines/viz.js#160]
The error message is `Identifier 'error' has already been declared`
since `error` is already declared in the catch clause.

**full.render.js**
```
if (typeof importScripts === "function") {
  var instance = Module();
  
  onmessage = function(event) {
    var id = event.data.id;
    var src = event.data.src;
    var options = event.data.options;
  
    try {
      var result = render(instance, src, options);
      postMessage({ id: id, result: result });
    } catch (error) {
<<<<<<< v2.0.0
      postMessage({ id: id, error: { message: error.message, fileName: error.fileName, lineNumber: error.lineNumber } });
=======
      var error = error instanceof Error
        ? { message: error.message, fileName: error.fileName, lineNumber: error.lineNumber }
        : { message: error.toString() };
      postMessage({ id: id, error: error });
>>>>>>> v2.1.1
    }
  }
}
```

**Comment by mdaines** [comment]
In what environment and situation are you seeing this? I think the referenced commit should address it, but knowing that might help prevent similar mistakes in the future.

**Comment by zetaraku** [comment]
I was using viz.js with webpack, it gave me the error below when packing my project.

```
ERROR in ./node_modules/viz.js/full.render.js 68:10
Module parse failed: Identifier 'error' has already been declared (68:10)
You may need an appropriate loader to handle this file type.
|       postMessage({ id: id, result: result });
|     } catch (error) {
>       var error = error instanceof Error
|         ? { message: error.message, fileName: error.fileName, lineNumber: error.lineNumber }
|         : { message: error.toString() };
 @ ./src/js/main/index.js 30:0-52 46:22-28 46:30-36
 @ ./src/index.js
```

**Comment by mdaines** [comment]
[v2.1.2-pre.1](https://github.com/mdaines/viz.js/releases/tag/v2.1.2-pre.1) (also on NPM) includes a fix for this.

It looks like you're importing the render script file. You can certainly do that, and I've added [an example showing that technique](https://github.com/mdaines/viz-examples/tree/master/webpack-no-worker). It fails to build with v2.1.1 (in the way you're seeing) and works with v2.1.2-pre.1.

However, if possible I would recommend something like [this example](https://github.com/mdaines/viz-examples/tree/master/webpack), where `file-loader` imports just the URL of the render script file using the ".render.js" suffix and then passes that to the `Viz` constructor:

https://github.com/mdaines/viz-examples/blob/0a9f7100aa73ff6f4ec4b4e150a842033a058ade/webpack/index.js#L1-L9

This avoids having Webpack actually look at the contents of the render script file, which is pretty big and will slow down the build.

**Comment by zetaraku** [comment]
Thanks for the quick fix and the suggestion and explanation of using file-loader! :D
My project now works fine!

Since the render script is a special case for the .js files, I use:
`import vizjsWorkerURL from 'file-loader!viz.js/full.render.js';`
to import it instead. :)
