### ISSUE TITLE
Can't build w/ emscripten 1.38.25 (latest)

### ISSUE THREAD

**Issue by wasbridge** [mdaines/viz.js#164]
`bschoenberg:viz.js bschoenberg$ make all
emcc --version | grep 1.38.25
emcc (Emscripten gcc/clang-like replacement) 1.38.25 (commit df648b43825d3ab1179886d3c78020ed890333d3)
emcc -Oz --memory-init-file 0 -s USE_ZLIB=1 -s MODULARIZE=0 -s WASM=0 -s LEGACY_VM_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s EXPORTED_FUNCTIONS="['_vizRenderFromString', '_vizCreateFile', '_vizSetY_invert', '_vizSetNop', '_vizLastErrorMessage', '_dtextract', '_Dtqueue']" -s EXPORTED_RUNTIME_METHODS="['Pointer_stringify', 'ccall', 'UTF8ToString']" -o build-full/module.js src/viz.c -I/Users/bschoenberg/code/personal/viz.js/prefix-full/include -I/Users/bschoenberg/code/personal/viz.js/prefix-full/include/graphviz -L/Users/bschoenberg/code/personal/viz.js/prefix-full/lib -L/Users/bschoenberg/code/personal/viz.js/prefix-full/lib/graphviz -lgvplugin_core -lgvplugin_dot_layout -lgvplugin_neato_layout -lcdt -lcgraph -lgvc -lgvpr -lpathplan -lexpat -lxdot

shared:ERROR: undefined exported function: "_Dtqueue"
make: *** [build-full/module.js] Error 1`

I cannot figure out how to make emscripten see _Dtqueue.  This is with a full graphviz build.  

I have confirmed that libcdt.a contains the symbol... here is a partial trace from nm libcdt.a

'dtlist_83611b7f.o:
-------- D Dtdeque
-------- D Dtlist
-------- D Dtqueue
-------- D Dtstack
-------- D _Dtdeque
-------- D _Dtlist
-------- D _Dtqueue
-------- D _Dtstack
-------- t dtlist
         U dtrestore
         U memcmp
         U strcmp'

Am I fighting with emscripten here or doing something else wrong?  What confuses me is that there are two Dtqueue symbols in the src one with a leading underscore and one without (cdt.h).

Any advise is much appreciated!

**Comment by mdaines** [comment]
I'm working on this in the https://github.com/mdaines/viz.js/tree/emscripten-1-38 branch. It builds, but some of the tests aren't working yet. (Browser tests in Chrome work, though.)

**Comment by wasbridge** [comment]
Hey FYI -- a friend of mine got it building and working for my needs, it too fails a test but doesn't appear to affect my usage...

https://github.com/bpowers/viz.js
