### ISSUE TITLE
Is synchronous use still possible?

### ISSUE THREAD

**Issue by christianvoigt** [mdaines/viz.js#165]
Hi, I am using Viz.Js as a Markdown-It plugin to generate graphs in Vuepress (see https://argdown.org). Because Markdown-It is a synchronous parser, I can not use the new asynchronous syntax (that is great for all my other use cases by the way). 

In #113 you wrote: 
> * Synchronous usage should still be possible.

Is this still possible? If not, could you make this work again?

**Comment by mdaines** [comment]
Closing because render(), etc are synchronous in v3.
