### ISSUE TITLE
Android Project 

### ISSUE THREAD

**Issue by developer-krushna** [mdaines/viz.js#205]
Hello sir . I want to make an Android app where user need to put some graph dot code and my project will compile the dot and show it as graph viz in WebView.. sir how can I start sir please.. help me also if you have any android project based on it then kindly share it with me .. I will highly greatful to you ♥️

Thank you 🙏

**Comment by mdaines** [comment]
I'm sorry, I can't provide help with this. If you have a specific bug or enhancement request for integrating Viz.js, please open another issue.
