### ISSUE TITLE
Types can not be imported with current package.json

### ISSUE THREAD

**Issue by Aderinom** [mdaines/viz.js#213]
Hello! 

With vites default ts-config, the types of this package can not be imported.

Solution:
In package.json - add the typings in the export object. E.g.:
```
  "exports": {
    "import": "./lib/viz-standalone.mjs",
    "require": "./lib/viz-standalone.js",
    "types": "./types/index.d.ts"
  },
```

Error:
```
Could not find a declaration file for module '@viz-js/viz'. 'C:/Users/user/Data/Projects/_private/newParseToUml/node_modules/.pnpm/@viz-js+viz@3.1.0/node_modules/@viz-js/viz/lib/viz-standalone.mjs' implicitly has an 'any' type.
  There are types at 'c:/Users/user/Data/Projects/_private/newParseToUml/node_modules/@viz-js/viz/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@viz-js/viz' library may need to update its package.json or typings. ts(7016)
```

Config: 
```
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noImplicitAny": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "typeAcquisition": { "enable": true, "include": ["./src/vite-env.d.ts"] },
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by mdaines** [comment]
It seems like package.json should refer to type declarations in this way going forward. I'll prepare a release to add this soon.

I should also look at the effect of specifying the "module" compiler option in the [type tests](https://github.com/mdaines/viz-js/tree/f09f27a684ce04dbdb813d4792a1c09811650c26/packages/viz/test/types).

Links to some documentation that refers to the "types" condition for my reference:

- https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
- https://nodejs.org/dist/latest-v21.x/docs/api/packages.html#community-conditions-definitions

**Comment by mdaines** [comment]
[3.2.2](https://github.com/mdaines/viz-js/releases/tag/release-viz-3.2.2) includes the types condition.
