### ISSUE TITLE
Dynamic font Family

### ISSUE THREAD

**Issue by GTharunesh** [mdaines/viz.js#215]
I need to use a different font family different from the default ones

**Comment by mdaines** [comment]
You can use the <a href="https://www.graphviz.org/docs/attrs/fontname/">fontname attribute</a> to specify the font used for label text. For example:

```dot
digraph {
  test [
    label="This is a test"
    fontname="Helvetica Neue"
  ]
}
```

https://viz-js.com/?dot=ZGlncmFwaCB7CiAgdGVzdCBbCiAgICBsYWJlbD0iVGhpcyBpcyBhIHRlc3QiCiAgICBmb250bmFtZT0iSGVsdmV0aWNhIE5ldWUiCiAgXQp9

The `text` element in the SVG will have the `font-family` attribute `"Helvetica Neue"`.

However, Graphviz doesn't know the measurements of these fonts and so the node might be sized incorrectly. You'll also see a warning that it's using the metrics for "Times" instead. If you know that a node needs to be a different width, for example, you could try adjusting its <a href="https://www.graphviz.org/docs/attrs/width/">width attribute</a>.

I'd like to have Viz.js use the actual size of the text for layout without needing to make manual adjustments, but I don't have a solution for that currently.

**Comment by mdaines** [comment]
Closing because this appears to be addressed by using the fontname attribute.
