### ISSUE TITLE
Strict mode but merge labels

### ISSUE THREAD

**Issue by nurulalamador** [mdaines/viz.js#217]
Currently if we use strict mode, it merge all the same transitions node, but problem is its show only label of last transition.

```
strict digraph {
  a -> b;
  b -> c [label = "Label 1"];
  b -> c [label = "Label 2"];
}
```
If we run this, it will show only "Label 2" between b and c transition in the graph.

Can we have any option in future to merge the labels and show like this: "Label 1, Label 2" ?

**Comment by mdaines** [comment]
No, since this is how Graphviz behaves, I would consider the change out of scope for Viz.js.

If you feel this would be a useful enhancement to Graphviz, please open an issue with that project.
