### ISSUE TITLE
I need to remove tooltip i.e title for entire graph. How can it be done

### ISSUE THREAD

**Issue by GTharunesh** [mdaines/viz.js#231]

**Comment by mdaines** [comment]
I can think of two possible approaches:

1. Modify the SVG to remove the `<title>` elements.
2. Specify something in [`nodeAttributes`](https://viz-js.com/api/#viz.RenderOptions.nodeAttributes) and related options.

If you can do this by specifying command-line options for the regular Graphviz `dot` command and the [`-N`](https://www.graphviz.org/doc/info/command.html#-N) option, you should be able to do this with the second approach. However, I don't know what attribute you'd use.

**Comment by magjac** [comment]
I think you can set tooltip=" " on the graph.

**Comment by mdaines** [comment]
That does replace the default graph tooltip, but there will still be a title element with a single space. Does that work for your use case @GTharunesh?

Starting with this graph:

```dot
digraph "my graph" {
  a -> b
}
```

Graphviz generates SVG with `<title>my graph</title>`, etc.

If I specify `tooltip=" "`, like this:

```dot
digraph "my graph" {
  tooltip=" "
  a -> b
}
```

That's equivalent to the command-line option `-Gtooltip=" "` or something like this with the Viz.js API:

```js
viz.renderSVGElement("digraph { ... }", { graphAttributes: { tooltip: " " } })
```

An anchor with a title is added to the graph: `<a xlink:title=" ">`.

I still see a tooltip, at least in Safari: (this is a screenshot, but the cursor didn't show up)

<img width="90" alt="Screenshot 2024-01-31 at 10 26 11 AM" src="https://github.com/mdaines/viz-js/assets/1383/2487b7cb-7b6e-45bc-8b77-2686e838c3b3">

Setting a blank string seems to be considered "not set" and the default tooltip is used.

**Comment by mdaines** [comment]
Closing because I view this as a question about Graphviz rather than Viz.js specifically.

I have some vague ideas about further customizing the SVG output from Viz.js that could address this but no concrete plan right now.
