### ISSUE TITLE
Positions will never change

### ISSUE THREAD

**Issue by VictorMRojas** [mdaines/viz.js#241]
digraph {
    node [style=filled];
    a [pos="5,3!"]; 
    b [pos="4,3!"]; 
    a -> b;
    bgcolor="transparent";
}

It gives the same result as

digraph {
    node [style=filled];
    a [pos="55464654,54654"]; 
    b [pos="65465,465456"]; 
    a -> b;
    bgcolor="transparent";
}

Nothing changes.

**Comment by mdaines** [comment]
Which layout engine are you using?

Note that the "pos" attribute isn't used by the "dot" layout engine: https://graphviz.org/docs/attrs/pos/

If you want to manually place nodes, you could try the "nop2" layout engine: https://graphviz.org/docs/layouts/nop2/

**Comment by VictorMRojas** [comment]
I don't know which layout is used by default, I didn't have any specified. I was just testing neato and fdp, but the one that points the most to what I was looking for is nop2,

Thank you for the info!

**Comment by mdaines** [comment]
Sorry, I suppose it's not necessarily even obvious that there _are_ other layout engines, given that Viz.js just has a method called `render`, and the layout engine is specified as an option. This is different from the Graphviz command-line programs, which are named for the layout engine. So you'll see examples using the `dot` program.

Anyway, the default for Viz.js is "dot": https://graphviz.org/docs/layouts/dot/
