### ISSUE TITLE
Editor doesn't have vertical scrolling anymore

### ISSUE THREAD

**Issue by asrelo** [mdaines/viz.js#277]
Before the series of releases in November, the editor frame had vertical scrolling. The layout never overflowed outside viewport (at least in my experience on wide desktops); when text in the editor was too long, the editor frame had scrolling.

Now, when text in the editor is too long, the editor resizes, causing the layout to overflow vertically, and page scrolling kicks in. Major undesired effects are that the search panel of the editor and list of errors/warnings end up on the very bottom of the page, and the rendered image ends up in the middle of the page.

Can be reproduced with any long text in the editor; the example graph "Clusters" might be enough.

Tested in Chrome 130.0, Firefox 130.0 on different screen sizes in horizontal orientation.

**Comment by mdaines** [comment]
Thanks for reporting this. I just reverted b2874f7d8611d033443223a5964b693a0a97d2a9 which introduced this issue.

**Comment by mdaines** [comment]
I deployed #278 which should fix this.
