### ISSUE TITLE
is that the attribute "splines" with "curved" value will be operational later?

### ISSUE THREAD

**Issue by MilWolf** [mdaines/viz.js#29]
everything is in the title, i tried it and it doesn't work. 
Maybe the functionality is not available?

**Comment by pmlemay** [comment]
Hi, I am trying to have only horizontal and vertical lines using ortho splines but it doesn't seem to work.
I am using svg format and dot engine. Is this normal?

**Comment by hmaalmi** [comment]
Hi,
@pmlemay i'm facing the same problem did you make it work ? thank you

**Comment by pmlemay** [comment]
Hey @hmaalmi,

I never got it to work and opened an issue a while ago (splines=ortho not working #40) but I chose to go with graphviz-ruby server side to achieve what I needed.

https://github.com/glejeune/Ruby-Graphviz/

**Comment by electronicsguy** [comment]
This problem still persists in Graphviz V2.38.0  on Windows.
