### ISSUE TITLE
Layout type: "sfdp" not recognized

### ISSUE THREAD

**Issue by DaniHaag** [mdaines/viz.js#34]
When I try to use the sfdp layout in with viz.js (@see http://www.graphviz.org/Documentation.php) I get an error message 
`Error: Layout type: "sfdp" not recognized. Use one of: circo dot fdp neato nop nop1 nop2 osage patchwork twopi`
I did not compile the viz.js I just used the version http://mdaines.github.io/viz.js/viz.js and adapted the form.html to support sfdp. 

You may easily reproduce it if you change the graph in http://mdaines.github.io/viz.js/form.html and add the layout attribute with layout="sfdp". It will display the error in the console.
``` dot
digraph G {
layout="sfdp";
	subgraph cluster_0 {
		style=filled;
		color=lightgrey;
		node [style=filled,color=white];
		a0 -> a1 -> a2 -> a3;
		label = "process #1";
	}

	subgraph cluster_1 {
		node [style=filled];
		b0 -> b1 -> b2 -> b3;
		label = "process #2";
		color=blue
	}
	start -> a0;
	start -> b0;
	a1 -> b3;
	b2 -> a3;
	a3 -> a0;
	a3 -> end;
	b3 -> end;

	start [shape=Mdiamond];
	end [shape=Msquare];
}
```

**Comment by mdaines** [comment]
This would require building and packaging [GTS](http://gts.sourceforge.net). I may add this option in the future.
