### ISSUE TITLE
Using viz.js distribution in WebWorker together with require.js

### ISSUE THREAD

**Issue by mstefaniuk** [mdaines/viz.js#41]
I'm developing an [online Graphviz dot editor](/mstefaniuk/graph-viz-d3-js) and I'm using old version of `viz.js`. I made a common module adding define wrapper around distribution code and I embedded it in WebWorker with use of `require()` as described in [its guideline](http://requirejs.org/docs/api.html#webworker).

Now I'm trying to upgrade to newer version but I have problems to use it in the same way. I'm receiving errors from initializing my module depending on `viz.js`. As far I understand (from generated code) there is support for WebWorker environment and `require.js` also. I'm not sure if it is supporting both together. If yes please give me an advice how to do that.

**Comment by mdaines** [comment]
The wrapper code for Viz.js used to reference the `window` object, so it didn't work well with Web Workers. I've changed this in the most recent version. Have a look at the gh-pages branch for an example of running Viz.js in a Web Worker: https://github.com/mdaines/viz.js/tree/gh-pages

**Comment by mstefaniuk** [comment]
@mdaines In your example `viz.js` is included into `WebWorker` with `importScripts()`. My question was how to do it the same with use of `require.js`.

**Comment by mdaines** [comment]
In that case, I don't know. I assume you'll have to either add the `define` wrapper yourself or use a shim: http://requirejs.org/docs/api.html#config-shim
