### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vasiqmz** [mdaines/viz.js#42]
I'm using the compile Viz.js 0.0.3 file. I'm able to see the output when it has 96 nodes but as soon as the nodes goes up from 96 I get the error.

Range Error: Maximum call stack size exceeded.

Anyone has faced this issue ?

**Comment by lkwg82** [comment]
Can you break it down to an example to debug it?

**Comment by vasiqmz** [comment]
<!DOCTYPE html>
    <html>
      <head>
    <meta charset="utf-8">
        <title>Viz.js</title>
      </head>
      <body>
    
    <script type="text/vnd.graphviz" id="cluster">
    digraph rule0{ 
	 node[shape=ellipse]; 
	 si1 -> 0 
	 node[shape=ellipse]; 
	 si1 -> si2 [style=dashed] 
	 node[shape=ellipse]; 
	 si2 -> 0 
	 node[shape=ellipse]; 
	 si2 -> si3 [style=dashed] 
	 node[shape=ellipse]; 
	 si3 -> 0 
	 node[shape=ellipse]; 
	 si3 -> si4 [style=dashed] 
	 node[shape=ellipse]; 
	 si4 -> 0 
	 node[shape=ellipse]; 
	 si4 -> si5 [style=dashed] 
	 node[shape=ellipse]; 
	 si5 -> si6 
	 node[shape=ellipse]; 
	 si5 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si6 -> 0 
	 node[shape=ellipse]; 
	 si6 -> si7 [style=dashed] 
	 node[shape=ellipse]; 
	 si7 -> si8 
	 node[shape=ellipse]; 
	 si7 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si8 -> 0 
	 node[shape=ellipse]; 
	 si8 -> si9 [style=dashed] 
	 node[shape=ellipse]; 
	 si9 -> 0 
	 node[shape=ellipse]; 
	 si9 -> si10 [style=dashed] 
	 node[shape=ellipse]; 
	 si10 -> si11 
	 node[shape=ellipse]; 
	 si10 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si11 -> 0 
	 node[shape=ellipse]; 
	 si11 -> si12 [style=dashed] 
	 node[shape=ellipse]; 
	 si12 -> si13 
	 node[shape=ellipse]; 
	 si12 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si13 -> 0 
	 node[shape=ellipse]; 
	 si13 -> si14 [style=dashed] 
	 node[shape=ellipse]; 
	 si14 -> 0 
	 node[shape=ellipse]; 
	 si14 -> si15 [style=dashed] 
	 node[shape=ellipse]; 
	 si15 -> 0 
	 node[shape=ellipse]; 
	 si15 -> si16 [style=dashed] 
	 node[shape=ellipse]; 
	 si16 -> 0 
	 node[shape=ellipse]; 
	 si16 -> si17 [style=dashed] 
	 node[shape=ellipse]; 
	 si17 -> 0 
	 node[shape=ellipse]; 
	 si17 -> si18 [style=dashed] 
	 node[shape=ellipse]; 
	 si18 -> si19 
	 node[shape=ellipse]; 
	 si18 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si19 -> 0 
	 node[shape=ellipse]; 
	 si19 -> si20 [style=dashed] 
	 node[shape=ellipse]; 
	 si20 -> si21 
	 node[shape=ellipse]; 
	 si20 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si21 -> si22 
	 node[shape=ellipse]; 
	 si21 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si22 -> 0 
	 node[shape=ellipse]; 
	 si22 -> si23 [style=dashed] 
	 node[shape=ellipse]; 
	 si23 -> si24 
	 node[shape=ellipse]; 
	 si23 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 si24 -> 0 
	 node[shape=ellipse]; 
	 si24 -> si25 [style=dashed] 
	 node[shape=ellipse]; 
	 si25 -> si26 
	 node[shape=ellipse]; 
	 si25 -> si26 [style=dashed] 
	 node[shape=ellipse]; 
	 si26 -> si27 
	 node[shape=ellipse]; 
	 si26 -> si27 [style=dashed] 
	 node[shape=ellipse]; 
	 si27 -> si28 
	 node[shape=ellipse]; 
	 si27 -> si28 [style=dashed] 
	 node[shape=ellipse]; 
	 si28 -> si29 
	 node[shape=ellipse]; 
	 si28 -> si29 [style=dashed] 
	 node[shape=ellipse]; 
	 si29 -> si30 
	 node[shape=ellipse]; 
	 si29 -> si30 [style=dashed] 
	 node[shape=ellipse]; 
	 si30 -> si31 
	 node[shape=ellipse]; 
	 si30 -> si31 [style=dashed] 
	 node[shape=ellipse]; 
	 si31 -> si32 
	 node[shape=ellipse]; 
	 si31 -> si32 [style=dashed] 
	 node[shape=ellipse]; 
	 si32 -> sp1 
	 node[shape=ellipse]; 
	 si32 -> sp1 [style=dashed] 
	 node[shape=ellipse]; 
	 sp1 -> sp2 
	 node[shape=ellipse]; 
	 sp1 -> sp2 [style=dashed] 
	 node[shape=ellipse]; 
	 sp2 -> sp3 
	 node[shape=ellipse]; 
	 sp2 -> sp3 [style=dashed] 
	 node[shape=ellipse]; 
	 sp3 -> sp4 
	 node[shape=ellipse]; 
	 sp3 -> sp4 [style=dashed] 
	 node[shape=ellipse]; 
	 sp4 -> sp5 
	 node[shape=ellipse]; 
	 sp4 -> sp5 [style=dashed] 
	 node[shape=ellipse]; 
	 sp5 -> sp6 
	 node[shape=ellipse]; 
	 sp5 -> sp6 [style=dashed] 
	 node[shape=ellipse]; 
	 sp6 -> sp7 
	 node[shape=ellipse]; 
	 sp6 -> sp7 [style=dashed] 
	 node[shape=ellipse]; 
	 sp7 -> sp8 
	 node[shape=ellipse]; 
	 sp7 -> sp8 [style=dashed] 
	 node[shape=ellipse]; 
	 sp8 -> sp9 
	 node[shape=ellipse]; 
	 sp8 -> sp9 [style=dashed] 
	 node[shape=ellipse]; 
	 sp9 -> sp10 
	 node[shape=ellipse]; 
	 sp9 -> sp10 [style=dashed] 
	 node[shape=ellipse]; 
	 sp10 -> sp11 
	 node[shape=ellipse]; 
	 sp10 -> sp11 [style=dashed] 
	 node[shape=ellipse]; 
	 sp11 -> sp12 
	 node[shape=ellipse]; 
	 sp11 -> sp12 [style=dashed] 
	 node[shape=ellipse]; 
	 sp12 -> sp13 
	 node[shape=ellipse]; 
	 sp12 -> sp13 [style=dashed] 
	 node[shape=ellipse]; 
	 sp13 -> sp14 
	 node[shape=ellipse]; 
	 sp13 -> sp14 [style=dashed] 
	 node[shape=ellipse]; 
	 sp14 -> sp15 
	 node[shape=ellipse]; 
	 sp14 -> sp15 [style=dashed] 
	 node[shape=ellipse]; 
	 sp15 -> sp16 
	 node[shape=ellipse]; 
	 sp15 -> sp16 [style=dashed] 
	 node[shape=ellipse]; 
	 sp16 -> di1 
	 node[shape=ellipse]; 
	 sp16 -> di1 [style=dashed] 
	 node[shape=ellipse]; 
	 di1 -> di2 
	 node[shape=ellipse]; 
	 di1 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di2 -> di3 
	 node[shape=ellipse]; 
	 di2 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di3 -> 0 
	 node[shape=ellipse]; 
	 di3 -> di4 [style=dashed] 
	 node[shape=ellipse]; 
	 di4 -> 0 
	 node[shape=ellipse]; 
	 di4 -> di5 [style=dashed] 
	 node[shape=ellipse]; 
	 di5 -> 0 
	 node[shape=ellipse]; 
	 di5 -> di6 [style=dashed] 
	 node[shape=ellipse]; 
	 di6 -> 0 
	 node[shape=ellipse]; 
	 di6 -> di7 [style=dashed] 
	 node[shape=ellipse]; 
	 di7 -> 0 
	 node[shape=ellipse]; 
	 di7 -> di8 [style=dashed] 
	 node[shape=ellipse]; 
	 di8 -> 0 
	 node[shape=ellipse]; 
	 di8 -> di9 [style=dashed] 
	 node[shape=ellipse]; 
	 di9 -> di10 
	 node[shape=ellipse]; 
	 di9 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di10 -> 0 
	 node[shape=ellipse]; 
	 di10 -> di11 [style=dashed] 
	 node[shape=ellipse]; 
	 di11 -> di12 
	 node[shape=ellipse]; 
	 di11 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di12 -> 0 
	 node[shape=ellipse]; 
	 di12 -> di13 [style=dashed] 
	 node[shape=ellipse]; 
	 di13 -> di14 
	 node[shape=ellipse]; 
	 di13 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di14 -> 0 
	 node[shape=ellipse]; 
	 di14 -> di15 [style=dashed] 
	 node[shape=ellipse]; 
	 di15 -> 0 
	 node[shape=ellipse]; 
	 di15 -> di16 [style=dashed] 
	 node[shape=ellipse]; 
	 di16 -> 0 
	 node[shape=ellipse]; 
	 di16 -> di17 [style=dashed] 
	 node[shape=ellipse]; 
	 di17 -> 0 
	 node[shape=ellipse]; 
	 di17 -> di18 [style=dashed] 
	 node[shape=ellipse]; 
	 di18 -> 0 
	 node[shape=ellipse]; 
	 di18 -> di19 [style=dashed] 
	 node[shape=ellipse]; 
	 di19 -> 0 
	 node[shape=ellipse]; 
	 di19 -> di20 [style=dashed] 
	 node[shape=ellipse]; 
	 di20 -> 0 
	 node[shape=ellipse]; 
	 di20 -> di21 [style=dashed] 
	 node[shape=ellipse]; 
	 di21 -> di22 
	 node[shape=ellipse]; 
	 di21 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di22 -> 0 
	 node[shape=ellipse]; 
	 di22 -> di23 [style=dashed] 
	 node[shape=ellipse]; 
	 di23 -> di24 
	 node[shape=ellipse]; 
	 di23 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di24 -> 0 
	 node[shape=ellipse]; 
	 di24 -> di25 [style=dashed] 
	 node[shape=ellipse]; 
	 di25 -> 0 
	 node[shape=ellipse]; 
	 di25 -> di26 [style=dashed] 
	 node[shape=ellipse]; 
	 di26 -> 0 
	 node[shape=ellipse]; 
	 di26 -> di27 [style=dashed] 
	 node[shape=ellipse]; 
	 di27 -> 0 
	 node[shape=ellipse]; 
	 di27 -> di28 [style=dashed] 
	 node[shape=ellipse]; 
	 di28 -> 0 
	 node[shape=ellipse]; 
	 di28 -> di29 [style=dashed] 
	 node[shape=ellipse]; 
	 di29 -> 0 
	 node[shape=ellipse]; 
	 di29 -> di30 [style=dashed] 
	 node[shape=ellipse]; 
	 di30 -> 0 
	 node[shape=ellipse]; 
	 di30 -> di31 [style=dashed] 
	 node[shape=ellipse]; 
	 di31 -> di32 
	 node[shape=ellipse]; 
	 di31 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 di32 -> 0 
	 node[shape=ellipse]; 
	 di32 -> dp1 [style=dashed] 
	 node[shape=ellipse]; 
	 dp1 -> 0 
	 node[shape=ellipse]; 
	 dp1 -> dp2 [style=dashed] 
	 node[shape=ellipse]; 
	 dp2 -> 0 
	 node[shape=ellipse]; 
	 dp2 -> dp3 [style=dashed] 
	 node[shape=ellipse]; 
	 dp3 -> 0 
	 node[shape=ellipse]; 
	 dp3 -> dp4 [style=dashed] 
	 node[shape=ellipse]; 
	 dp4 -> 0 
	 node[shape=ellipse]; 
	 dp4 -> dp5 [style=dashed] 
	 node[shape=ellipse]; 
	 dp5 -> 0 
	 node[shape=ellipse]; 
	 dp5 -> dp6 [style=dashed] 
	 node[shape=ellipse]; 
	 dp6 -> 0 
	 node[shape=ellipse]; 
	 dp6 -> dp7 [style=dashed] 
	 node[shape=ellipse]; 
	 dp7 -> 0 
	 node[shape=ellipse]; 
	 dp7 -> dp8 [style=dashed] 
	 node[shape=ellipse]; 
	 dp8 -> 0 
	 node[shape=ellipse]; 
	 dp8 -> dp9 [style=dashed] 
	 node[shape=ellipse]; 
	 dp9 -> 0 
	 node[shape=ellipse]; 
	 dp9 -> dp10 [style=dashed] 
	 node[shape=ellipse]; 
	 dp10 -> dp11 
	 node[shape=ellipse]; 
	 dp10 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 dp11 -> 0 
	 node[shape=ellipse]; 
	 dp11 -> dp12 [style=dashed] 
	 node[shape=ellipse]; 
	 dp12 -> dp13 
	 node[shape=ellipse]; 
	 dp12 -> 0 [style=dashed] 
	 node[shape=ellipse]; 
	 dp13 -> 0 
	 node[shape=ellipse]; 
	 dp13 -> dp14 [style=dashed] 
	 node[shape=ellipse]; 
	 dp14 -> 0 
	 node[shape=ellipse]; 
	 dp14 -> dp15 [style=dashed] 
	 node[shape=ellipse]; 
	 dp15 -> 0 
	 node[shape=ellipse]; 
	 dp15 -> dp16 [style=dashed] 
	 node[shape=ellipse]; 
	 dp16 -> 0 
	 node[shape=ellipse]; 
	 dp16 -> pr1 [style=dashed] 
	 node[shape=ellipse]; 
	 pr1 -> 0 
	 node[shape=ellipse]; 
	 pr1 -> pr2 [style=dashed] 
	 node[shape=ellipse]; 
	 pr2 -> 0 
	 node[shape=ellipse]; 
	 pr2 -> pr3 [style=dashed] 
	 node[shape=ellipse]; 
	 pr3 -> 0 
	 node[shape=ellipse]; 
	 pr3 -> pr4 [style=dashed] 
	 node[shape=ellipse]; 
	 pr4 -> 0 
	 node[shape=ellipse]; 
	 pr4 -> pr5 [style=dashed] 
	 node[shape=ellipse]; 
	 pr5 -> 0 
	 node[shape=ellipse]; 
	 pr5 -> pr6 [style=dashed] 
	 node[shape=ellipse]; 
	 pr6 -> 0 
	 node[shape=ellipse]; 
	 pr6 -> pr7 [style=dashed] 
	 node[shape=ellipse]; 
	 pr7 -> 0 
	 node[shape=ellipse]; 
	 pr7 -> pr8 [style=dashed] 
	 node[shape=ellipse]; 
	 pr8 -> 0 
	 node[shape=ellipse]; 
	 pr8 -> 1 [style=dashed]; 

     }
</script>
    
    
    
    <script src="../viz.js"></script>
    <script>
      
      function inspect(s) {
        return "<pre>" + s.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;") + "</pre>"
      }
      
      function src(id) {
        return document.getElementById(id).innerHTML;
      }
      
      function example(id, format, engine) {
        var result;
        try {
          result = Viz(src(id), format, engine);
          if (format === "svg")
            return result;
          else
            return inspect(result);
        } catch(e) {
          return inspect(e.toString());
        }
      }
      
      document.body.innerHTML += "<p>Dot examples from the <a href=\"http://graphviz.org/Gallery.php\">Graphviz gallery</a>. Neato example from <a href=\"http://www.graphviz.org/pdf/neatoguide.pdf\">NEATO User's Manual</a>.</p>"
      
      document.body.innerHTML += "<h1>Cluster (svg output)</h1>";
      document.body.innerHTML += example("cluster", "svg");
      
      
    </script>
    
      </body>
    </html>

Above is the entire source code I'm pasting. If I remove the Pr0 - Pr8 nodes then it is able to print it but then after Pr4 i will start getting the error.
