### ISSUE TITLE
Cannot use images in svg

### ISSUE THREAD

**Issue by apfelgluck** [mdaines/viz.js#43]
Hello,

I trying to generate a SVG including local images (the idea is to change local path to url once the svg is done), but i cant find where to put the images.
the svg is generate without them.

for the Dot : 

digraph g{
  mynode[image="image.png", label=""];
}

i get the message : 

Warning: No such file or directory while opening image.png Warning: No or improper image="image.png" for node "mynode" 

and the svg : 

"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="62pt" height="44pt"
 viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
<title>g</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>

<g id="node1" class="node"><title>mynode</title>
<ellipse fill="none" stroke="black" cx="27" cy="-18" rx="27" ry="18"/>
</g>
</g>
</svg>"

i tried several places but i couldnt make it work.

any ideas ?

thanks for the great work anyway

**Comment by jaime-olivares** [comment]
Hi @apfelgluck, did you find a way to use images in shapes?
