### ISSUE TITLE
Error reporting with subsequent viz.js calls

### ISSUE THREAD

**Issue by mstefaniuk** [mdaines/viz.js#46]
When calling `Viz()` only first time error line matches original input. Next calls return errors on incrementing lines. Some errors are reported only first few calls. Example of this behavior can be viewed [on fiddle](http://jsfiddle.net/a76dne8u/4/).

Also reporting on `console` is little bit inconvenient but it is another issue.

**Comment by mdaines** [comment]
That's pretty odd. I'll have a look.

Proper error reporting is next on my list.
