### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by vvakame** [mdaines/viz.js#47]
please publish viz.js to npm.
Do you merge pull request if I make a package.json and add [UMD](https://github.com/umdjs/umd) support?

* add package.json
* add UMD pattern. It make possible to load by browser and node.js context.
* publish to npm

usage.

```
$ cat sample.js
var Viz = require("viz.js");
var result = Viz("digraph g { a -> b; }");
console.log(result);
$ node sample.js
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: g Pages: 1 -->
<svg width="62pt" height="116pt"
 viewBox="0.00 0.00 62.00 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>g</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-112 58,-112 58,4 -4,4"/>
<!-- a -->
<g id="node1" class="node"><title>a</title>
<ellipse fill="none" stroke="black" cx="27" cy="-90" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-85.8" font-family="Times,serif" font-size="14.00">a</text>
</g>
<!-- b -->
<g id="node2" class="node"><title>b</title>
<ellipse fill="none" stroke="black" cx="27" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-13.8" font-family="Times,serif" font-size="14.00">b</text>
</g>
<!-- a&#45;&gt;b -->
<g id="edge1" class="edge"><title>a&#45;&gt;b</title>
<path fill="none" stroke="black" d="M27,-71.6966C27,-63.9827 27,-54.7125 27,-46.1124"/>
<polygon fill="black" stroke="black" points="30.5001,-46.1043 27,-36.1043 23.5001,-46.1044 30.5001,-46.1043"/>
</g>
</g>
</svg>
```

**Comment by mdaines** [comment]
At this time, I'm leaning toward not doing this, but I'm interested to know why you want to.

What do you see as the advantage of being able to use Viz.js from node? If you have node available to you (ie, you're not in the browser environment) can't you just use Graphviz?

**Comment by vvakame** [comment]
1. I want to use viz.js in GitHub [Atom](https://atom.io/).
atom plugin can access to npm/apm repository. If user must install Graphviz manually, it is not convenient.

2. in browser context.
browser app are built with browserify recently.
It can process npm packages.
please see this web page. http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by mstefaniuk** [comment]
I would suggest to put `viz.js` on Bower.

**Comment by mdaines** [comment]
I've published a Viz.js package on Bower ("viz.js") since I think it's a better fit than npm.

I have also changed the way the `Viz` function is exported to hopefully make it easier to use with Browserify. See 38bee06c39a9603969d65e18132b4d07337e7fea.

**Comment by vvakame** [comment]
umm..

**Comment by hashrock** [comment]
How about publishing to both bower and npm?
Some people prefer npm than bower.

**Comment by mdaines** [comment]
Maybe it would be OK. However, there is already a Viz.js npm module published by someone else! https://www.npmjs.com/package/viz.js

I will contact the maintainer.

**Comment by vvakame** [comment]
thanks! :+1:

**Comment by hashrock** [comment]
thanks :)

**Comment by mdaines** [comment]
Viz.js is now on npm.

**Comment by vvakame** [comment]
thanks a lot!
