### ISSUE TITLE
SVG to PNG

### ISSUE THREAD

**Issue by caseywatts** [mdaines/viz.js#48]
Hi!
I've done some work related to this project I wanted to share :D

github.com/caseywatts/graphviz-repl

Specifically, I wanted the output of `viz.js` to be an image I could easily copy-paste into another environment (like Slack). 

If we take the svg output from graphviz, we can convert it to a PNG by dipping it through the canvas.
`var svg_data = Viz(dotData, {'format':"svg", 'engine': type});`
`var png_data = svgToPngConverter.svg_string_to_png_data(svg_data);`
`$('img#some-specific-image').attr('src', png_data);`

This is a hack lol but so is viz.js :heart: 
```
var svgToPngConverter = {
  svg_string_to_png_data: function (svg_string) {
    var svg_xml = this.svg_string_to_xml(svg_string);
    var img = this.svg_img_from_xml(svg_xml);
    var png_data = this.svg_img_to_png_data_via_canvas(img);
    return png_data;
  },
  svg_string_to_xml: function (svg_string) {
    var parser = new DOMParser();
    var svg_xml = parser.parseFromString(svg_string, "image/svg+xml").
...getElementsByTagName('svg')[0];
    return svg_xml;
  },
  svg_img_from_xml: function (svg_xml) {
    var new_width = svg_xml.width.baseVal.valueInSpecifiedUnits;
    var new_height = svg_xml.height.baseVal.valueInSpecifiedUnits;
    var svg_data = '<svg xmlns="http://www.w3.org/2000/svg" width="' + new_width +
    '" height="' + new_height + '">' + svg_xml.innerHTML + '</svg>';
    var img = new Image();
    img.src = "data:image/svg+xml;utf8," + svg_data;
    return img;
  },
  svg_img_to_png_data_via_canvas: function (svg_img) {
    var mycanvas = document.createElement('canvas');
    mycanvas.width = svg_img.width;
    mycanvas.height = svg_img.height;
    var ctx = mycanvas.getContext("2d");
    ctx.drawImage(svg_img, 0, 0);
    return mycanvas.toDataURL("image/png");
  }
};
```

I wanna PR this somehow but I'm not sure: where in the code base / if it's appropriate to add to this project / also this is untested.

:tada: :)

**Comment by mdaines** [comment]
Interesting. I have been wondering about supporting PNG output, but on the Graphviz/Emscripten side of things.

What about the API? It would be nice to be able to say something like this:

```
Viz("digraph { a -> b }", { format: "png" }) // => a data uri
```

**Comment by thoorp** [comment]
Absolutely!

**Comment by mdaines** [comment]
I would have thought you'd need to wait until the SVG image loads in order to draw it?

Like this: https://gist.github.com/mdaines/b3a9fec09528533c7a50

**Comment by caseywatts** [comment]
yes! thank you @mdaines :)
