### ISSUE TITLE
html-like labels

### ISSUE THREAD

**Issue by jcable** [mdaines/viz.js#51]
```
digraph G {
  "Welcome" [ shape=box, label=<
  <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
  <TR><TD>left</TD><TD PORT="f1">mid dle</TD><TD PORT="f2">right</TD></TR> 
  </TABLE>> ];
    "Welcome" -> "To";
    "To" -> "Web";
    "To" -> "GraphViz!";
  }
```

results in the error:

  Warning: Not built with libexpat. Table formatting is not available. in label of node Welcome

(sorry can't work out how to stop Markdown intepreting the table).

I'm up for helping implement this if it makes sense.

**Comment by mdaines** [comment]
Which build of Viz.js are you using? The example you quoted should be supported -- it works for me on the demo site: http://mdaines.github.io/viz.js/

I've edited your issue to fix the Markdown formatting. You need to use backticks on both sides of the code block, and put them on lines by themselves, like this:

    ```
    digraph G {
    ...
    }
    ```

**Comment by jcable** [comment]
Thanks, you are right. I had some problems with the latest build which I have now resolved so the experiments I did where the html-like labels did not work were the version here: http://webgraphviz.com/
