### ISSUE TITLE
large file out of memory 

### ISSUE THREAD

**Issue by jessyZu** [mdaines/viz.js#57]
cosole error in chrome:

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

Then,I try to add this code before Viz.js

```

<script> 
        var Module = {
             TOTAL_MEMORY: [537395200]
        } 
   </script>
```

but it can't works

**Comment by mdaines** [comment]
The `Module` variable this refers to is hidden inside a closure. If you really want to do this, I would try one of the following:

1) Build Viz.js with a modified src/pre.js.
2) Edit the Viz.js release. You can find the closure and the Emscripten Module variable at the beginning of the file.

**Comment by guoguogis** [comment]
set default value of TOTAL_MEMORY ,like this:
ma=e.TOTAL_MEMORY||537395200

**Comment by mdaines** [comment]
Viz.js now supports the `totalMemory` option:

```javascript
Viz(src, { totalMemory: 537395200 });
```

**Comment by shicks** [comment]
This option doesn't seem to work in 2.1.2 when viz.js is loaded in Node using `require('viz.js/full.render.js')`.

A usable workaround is as follows:

```js
const viz = new Viz({Module: () => Module({TOTAL_MEMORY: 1<<25}), render});
```
