### ISSUE TITLE
Build error on latest commit, Emscripten 1.35.0

### ISSUE THREAD

**Issue by adamserafini** [mdaines/viz.js#60]
I get an error when trying to compile the latest commit on Master (119049b0de8b319492f86ef34e1ade4af8d2efde) from source.

For reference, here is the output of `emcc -v` on my machine

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
INFO:root:(Emscripten: Running sanity checks)
```

The output from the build is quite large so I've posted it into a Gist [here](https://gist.github.com/adamserafini/7ef8bb3011cfc5fa1d9e).

(Perhaps I shouldn't be using latest commit on Master?)

**Comment by adamserafini** [comment]
Just to add some more information: I am able to *successfully* build release [v1.3.0](https://github.com/mdaines/viz.js/releases/tag/v1.3.0). So the problem is introduced somewhere in latest 2x commits.

**Comment by mdaines** [comment]
In general, master should build with the latest Emscripten SDK.
