### ISSUE TITLE
how to I self host viz.js?

### ISSUE THREAD

**Issue by ddonindia** [mdaines/viz.js#61]
I have installed viz.js using npm install on my rpi 2 box.
But how do I host it to access it in browser.

**Comment by ddonindia** [comment]
is this project still maintained ?

**Comment by matkokvesic** [comment]
Try with this: https://github.com/matkokvesic/express-graphviz

**Comment by ddonindia** [comment]
Thanks @matkokvesic.
I am getting "Error: syntax error in line 1 near '򀀀" error while running it.
Any idea how to fix it ?

**Comment by ddonindia** [comment]
Thanks @matkokvesic :+1:
