### ISSUE TITLE
Not able to open the diagram when there are multiple calls for the same node.

### ISSUE THREAD

**Issue by swapi2689** [mdaines/viz.js#64]
I am not able to open the diagram when there are multiple calls for the same node, from different nodes/edges, but say when I reduce the calling statement for the specific node which has been called multiple time, the graph is drawn. 
I am using viz.js
 here is what the calling statements looks like and when I delete 20 or so, graph is generated fine.

31->563
44->563
51->563
56->88
69->574
70->592
94->563
110->563
120->563
130->563
136->563
140->563
148->563
159->563
170->563
181->563
191->563
201->563
211->563
221->563
232->563
243->563
253->563
263->563
273->563
284->563
295->563
305->563
315->563
326->563
337->563
347->563
358->563
369->563
380->563
391->563
402->563
413->563
423->563
433->563
443->563
449->563
453->563
457->563
465->563
476->563
487->563
497->563
507->563
517->563
527->563
537->563
547->563
557->563

**Comment by mdaines** [comment]
The following graph renders for me in the [web interface](http://mdaines.github.io/viz.js/). Can you include the entire input you used?

```dot
digraph {
31->563
44->563
51->563
56->88
69->574
70->592
94->563
110->563
120->563
130->563
136->563
140->563
148->563
159->563
170->563
181->563
191->563
201->563
211->563
221->563
232->563
243->563
253->563
263->563
273->563
284->563
295->563
305->563
315->563
326->563
337->563
347->563
358->563
369->563
380->563
391->563
402->563
413->563
423->563
433->563
443->563
449->563
453->563
457->563
465->563
476->563
487->563
497->563
507->563
517->563
527->563
537->563
547->563
557->563
}
```
