### ISSUE TITLE
Tooltip attribute not recognized

### ISSUE THREAD

**Issue by hammenm** [mdaines/viz.js#66]
I try to get a tooltip on one label, but it does not appear in the rendered svg. The code is below :

```
digraph graphe {
    node [shape=record];
    entity [label=<
    <TABLE BORDER="0">
    <TR><TD TOOLTIP="foo">NameEntity</TD></TR><HR/>
    <TR><TD>Name1 : type1</TD></TR>
    <TR><TD>Name2 : type2</TD></TR>
    </TABLE>>];
}
```

I expect to be written "foo" in a tooltip window when I left the cursor on the word NameEntity.
I tried to follow the specification of a dot file. Maybe there is a mistake in the text or it may not be implemented.

**Comment by pimgeek** [comment]
But you can use Graphviz's own node tooltip:

    node1 [style=filled tooltip="hello"];

**Comment by hammenm** [comment]
The problem is that I wanted do add different tooltip for each line.
Considering a multi-line label, like the example below, the tooltip is assigned to the whole label.
```
entity [style=filled tooltip="hello" label = "{firstText \n secondText}"];
```
There may be a trick to force it to have two tooltip on "one" node.

**Comment by mdaines** [comment]
The command-line DOT tool appears to have the same behavior. You can assign an xlink:title attribute to the text in that cell if you use the HREF attribute, however:

```dot
digraph graphe {
    node [shape=record];
    entity [label=<
    <TABLE BORDER="0">
    <TR><TD HREF="#" TITLE="foo">NameEntity</TD></TR><HR/>
    <TR><TD TITLE="foo">Name1 : type1</TD></TR>
    <TR><TD>Name2 : type2</TD></TR>
    </TABLE>>];
}
```
