### ISSUE TITLE
Is this possible to add class in the generated SVG?

### ISSUE THREAD

**Issue by tedwong** [mdaines/viz.js#69]
For example, I would like make the shape have class or an id for js interaction. Any advance?

**Comment by jaime-olivares** [comment]
There won't be advance. This project is officially frozen.

**Comment by rstacruz** [comment]
I doubt it. You're better off making a transformation step that "fixes" up the SVG output.

**Comment by mdaines** [comment]
It is possible to add an id attribute to SVG elements using the [id attribute](http://www.graphviz.org/content/attrs#did) in the DOT language. For example:

```dot
digraph G {
  a [id="aardvark"];
  b [id="bat"];
  a -> b;
}
```

The `<g>` elements for the nodes will have the ids specified.

**Comment by another-guy** [comment]
@mdaines The `id="some_id"` approach works with edges as well. Thank you for a hint!

**Comment by mdaines** [comment]
> @mdaines The `id="some_id"` approach works with edges as well. Thank you for a hint!

You can also use the [`class` attribute](https://graphviz.org/docs/attrs/class/). This is supported in Viz.js 3.x. It may also be supported in later 2.x versions, but I haven't verified that.

```
digraph {
  a [class="abc"]
}
```

In SVG output, you'll get this:

```
<g id="node1" class="node abc">
```
