### ISSUE TITLE
Update graphviz to 2.40.1

### ISSUE THREAD

**Issue by IvanGoncharov** [mdaines/viz.js#73]
Here is changelog:
https://github.com/ellson/graphviz/blob/master/ChangeLog#L19
I'm very interested in:
>network-simplex fixes and optimization (Stephen North)

> Added JSON output format, -Tjson  (Emden Gansner)

**Comment by mdaines** [comment]
Addressed in ba53f68dbfe301cec99a593b72f5772b4cfc0976.

**Comment by IvanGoncharov** [comment]
@mdaines Thank you 🎉

**Comment by IvanGoncharov** [comment]
@mdaines Can you please release update package?
