### ISSUE TITLE
`eval` issue

### ISSUE THREAD

**Issue by shd101wyy** [mdaines/viz.js#75]
Hi,

First of all, thank you very much for this awesome library :) 
I am writing a markdown package called [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) for atom editor, and I am using your library to render dot language graph.  
It was working fine with viz.js version `1.3.0`, however after I upgraded it to `1.7.0`, it started casuing issue like:   
> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"  

It seems that the `eval` function caused the issue, but version `1.3.0` doesn't have this problem.  
Any idea how to solve this problem?  

Thanks

**Comment by shd101wyy** [comment]
I just tried modifying the first line  
`var e;e||(e=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));`
to  
`var e;e||(e= Module || {});`  
and it seems to be working.
not sure if that's the reason.

**Comment by mdaines** [comment]
That call to `eval()` is emitted by Emscripten. We can replace it in the generated code, but I would prefer to address this by changing Emscripten settings if possible.

Emscripten does provide a `NO_DYNAMIC_EXECUTION` setting which removes calls to `eval()`, etc. but if that's used it won't run Closure Compiler. That increases the size of `viz.js` by about 100KB. I'll look at ways to use that setting but also avoid the file size increase.

**Comment by lostplan** [comment]
`eval` is pretty bad; modern sites with a content security policy will block its use anyway.

And now this problem is now spreading through your dependents (I found this issue after having trouble with graphql-voyager).

I would suggest providing an eval-free version by default, with a smaller version available for those with special requirements.
