### ISSUE TITLE
Large output (3mb) when used with webpack

### ISSUE THREAD

**Issue by TexAgg** [mdaines/viz.js#76]
I was trying out Viz.js with Webpack, and the resulting bundle was a massive 3 megabytes, even after minification, even though my entry point is only 5 lines, and there are no other modules being imported.
```
var Viz = require('viz.js');
var graph = require('./graph.txt');

var image = Viz(graph, { format: "png-image-element" });
document.body.appendChild(image);
```
`graph.txt` is only 8 kb, so I don't think that is what's causing the large size.
I don't know if its an optimization issue or I'm just using Webpack incorrectly.

Here is my `webpack.config.js`.
```
var webpack = require('webpack');
var path = require('path');

module.exports = {
	entry: "./main.js",
	output: {
		path: __dirname + "/dist",
		filename: "main.min.js"
	},
	plugins: [
		new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false })
	],
	// https://github.com/josephsavona/valuable/issues/9
	node: {
		fs: "empty"
	},
	module: {
		rules: [
			{
				test: /\.txt$/,
				use: 'raw-loader'
			}
		]
	}
};
```

**Comment by mdaines** [comment]
I assume the resulting bundle includes Viz.js, which is 2.3MB as of the [1.7.0 release](https://github.com/mdaines/viz.js/releases/tag/v1.7.0), the bulk of which is already minified using Closure Compiler.

Did you not want to include Viz.js in your bundle?

**Comment by TexAgg** [comment]
Nevermind I didnt realise the relase was that big, i thought a bunch of extra files were being included.
