### ISSUE TITLE
Add support for lhead/ltail

### ISSUE THREAD

**Issue by Chaz6** [mdaines/viz.js#79]
In order to connect subgraphs, it is necessary to use lhead and/or ltail as in the following example:-

```
# http://www.graphviz.org/content/cluster

digraph G {

	subgraph cluster_0 {
		style=filled;
		color=lightgrey;
		node [style=filled,color=white];
		a0 -> a1 -> a2 -> a3;
		label = "process #1";
	}

	subgraph cluster_1 {
		node [style=filled];
		b0 -> b1 -> b2 -> b3;
		label = "process #2";
		color=blue
	}
	start -> a0 [lhead=cluster_0];
	start -> b0;
	a1 -> b3 [ltail=cluster_0,lhead=cluster_1];
	b2 -> a3;
	a3 -> a0;
	a3 -> end;
	b3 -> end [ltail=cluster_1];

	start [shape=Mdiamond];
	end [shape=Msquare];
}
```

**Comment by mdaines** [comment]
Viz.js should support these attributes. The output of the regular `dot` program on the command-line is identical to Viz.js for this example as far as I can tell.

According to the documentation, if you want to use the `lhead` and `ltail` attributes you need to set the graph's `compound` attribute to `true`. http://www.graphviz.org/content/attrs#dlhead
