### ISSUE TITLE
viz-lite.js utf-8 conversion fails

### ISSUE THREAD

**Issue by jorgenhojdmo** [mdaines/viz.js#80]
When using viz.js characters like åäö is working properly. In viz-lite.js the following error is generated:

Uncaught TypeError: e.UTF8ToString is not a function
    at Object.A [as Pointer_stringify] (viz-lite.js:35)

**Comment by mdaines** [comment]
@jorgenhojdmo I can't seem to reproduce this problem. Can you paste the graph you're seeing the error with?

**Comment by jorgenhojdmo** [comment]
```
digraph {
      rankdir=LR;
      node [style="filled"];
      graph [bgcolor="gray"];
       start [ id="start" label="Start" fillcolor="white"];
 stop [ id="stop" label="Stop" fillcolor="white"];
 start -> stop [id="ne2" label="åäö"  color="red" ];

```
The conversion executed from the following html file saved in UTF-8 format hosted by a Node server running on OS X El Capitan and works fine with viz.js and fails with viz-lite.js

```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
    </head>
<body>
<div id="parser"></div>
<script src="viz.js"></script>
<script>
 ...
    function dgraphToSvg(dgraph) {
        svgString = Viz(dgraph, { format: "svg" } );     
        return svgString;
    }
</script>
</body>
</html>
```

**Comment by mdaines** [comment]
I can't seem to reproduce this error using the example graph you've given. Please feel free to re-open this issue if this is still a problem.
