### ISSUE TITLE
Document which font names are safe to use

### ISSUE THREAD

**Issue by mdaines** [mdaines/viz.js#82]
See #81. Viz.js doesn't include fontconfig or have access to any system fonts, so Graphviz must fall back on its own metrics to estimate text span sizes. If other names are used, it may not measure text correctly.

See also:

https://github.com/ellson/graphviz/blob/master/lib/common/textspan.c
https://github.com/ellson/graphviz/blob/master/doc/fontfaq.txt

**Comment by magjac** [comment]
Is there some way for me to find out this info myself? Trial and error gave Courier as a working font, but me no like.

**Comment by mstefaniuk** [comment]
[In this document](http://www.graphviz.org/doc/fontfaq.txt) you can find names of fonts supported by Graphviz natively.

**Comment by mdaines** [comment]
I believe it is Times, Arial, Helvetica, and Courier.

**Comment by magjac** [comment]
I went for Helvetica and it's ok for now at least.

**Comment by magjac** [comment]
Strange. I got Marcins comment by email, but I don't see it on github.

**Comment by mstefaniuk** [comment]
@magjac I wrote this but just after that I had noticed that this link is already in first comment...

**Comment by mdaines** [comment]
Added note to README in ed49525397aa990544c86cfdc0c7ef1ecee700a1.
