### ISSUE TITLE
webpack compile fail, require('fs'), module not found

### ISSUE THREAD

**Issue by li-yinan** [mdaines/viz.js#83]
viz does check running environment. when running in node envrionment viz `require('fs')`.
I use viz in browser, but the `require('fs')` is still there, webpack can't find fs module and compile fail
How can I use viz with webpack?

**Comment by mdaines** [comment]
I was looking at this recently and found two possible solutions:

1) Ask webpack to replace "fs", etc. with empty objects.

```javascript
  // ...

  node: {
    fs: "empty",
    path: "empty",
    crypto: "empty"
  },

 // ...
```

2) Use script-loader:

```javascript
import vizScriptLoader from 'script-loader!viz.js';
```

**Comment by mdaines** [comment]
The next release will include a "browser" property in package.json that appears to address this problem.
