### ISSUE TITLE
support click event handler for nodes and edges

### ISSUE THREAD

**Issue by colorpump** [mdaines/viz.js#84]
I would like to have the possiblility of adding click event handlers to nodes and edges.

It could look like
```javascript
Viz('digraph { a -> b; a [onclick="doSth()"]}')
```

Is there a way to do that? Or could it be implemented?

**Comment by mdaines** [comment]
Viz.js doesn't support this directly, but you can add "id" attributes to elements in the SVG output by using the "id" attribute:

```dot
digraph { a -> b; a[id="a"]; }
```

After inserting the SVG into the document, you could set up an event handler by querying for the id you set.
