### ISSUE TITLE
Render a .dot from a URL?

### ISSUE THREAD

**Issue by pfalcon** [mdaines/viz.js#85]
This must be a FAQ, yet nothing in README, no example in the repo. I have a file somewhere on the net, e.g. https://pfalcon.github.io/xtensa-subjects/2.0.0-p20160809/callgraph.dot . All I want is a link I can give users to be able to browse that .dot, even if the link has to be on the same domain, like https://pfalcon.github.io/viz.js.foo?dot=/xtensa-subjects/2.0.0-p20160809/callgraph.dot

**Comment by pfalcon** [comment]
https://pfalcon.github.io/viz.js/dotview.html?https://raw.githubusercontent.com/pfalcon/xtensa-subjects/master/2.0.0-p20160809/callgraph.dot

**Comment by pfalcon** [comment]
https://github.com/mdaines/viz.js/pull/86

**Comment by pfalcon** [comment]
Permanent location of the viewer: https://pfalcon.github.io/wdot/v.html

**Comment by mdaines** [comment]
Thank you for the request and PR. At this time I feel that the examples showing rendering from a literal string are sufficient, but I will consider including something like this in the documentation in the future.
