### ISSUE TITLE
Dot engine doesn't work for complex graph

### ISSUE THREAD

**Issue by helios2905** [mdaines/viz.js#87]
Dot parsing doesn't work for complex graph. Tested using attached dot definition below in http://viz-js.com/

[graphDefinition.txt](https://github.com/mdaines/viz.js/files/972634/graphDefinition.txt)

**Comment by helios2905** [comment]
This seems to work for version 1.5.1 but starts breaking from version 1.6.0 onwards.

**Comment by mdaines** [comment]
This graph fails with the same error for me in the regular Graphviz program (dot version 2.40.1) so you may want to report this to the [graphviz project](https://github.com/ellson/graphviz). I did notice that removing the `splines=ortho;` attribute allows the graph to render without error.
