### ISSUE TITLE
"Cannot enlarge memory arrays" error processing large graph

### ISSUE THREAD

**Issue by aragozin** [mdaines/viz.js#89]
I've got following error message trying process large graph. I suppose it is referring to Emscripten compile options.

`Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ") at Error at Ga (http://viz-js.com/bower_components/viz.js/viz.js:49:124) at Fa (http://viz-js.com/bower_components/viz.js/viz.js:49:22) at v (http://viz-js.com/bower_components/viz.js/viz.js:1183:101) at Function.ba [as Wa] (http://viz-js.com/bower_components/viz.js/viz.js:34:488) at uc (http://viz-js.com/bower_components/viz.js/viz.js:1103:161) at eQ (http://viz-js.com/bower_components/viz.js/viz.js:1168:7157) at zz (http://viz-js.com/bower_components/viz.js/viz.js:1160:92650) at yz (http://viz-js.com/bower_components/viz.js/viz.js:1160:92582) at Wi (http://viz-js.com/bower_components/viz.js/viz.js:1163:4858) at Vi (http://viz-js.com/bower_components/viz.js/viz.js:1163:4250) If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information`

**Comment by mdaines** [comment]
When processing a large graph, you can try using the `totalMemory` option. For example:

```javascript
Viz(src, { totalMemory: 32 * 1024 * 1024 })
```

**Comment by rfreitas** [comment]
It doesn't seem that this option is working anymore.
Also by inspecting the code I was not see evidence that this parameter is being passed down.

PS. I'm using url web workers

**Comment by aleen42** [comment]
@mdaines any new set suggestions for working around.?

**Comment by dkuebric** [comment]
+1 would also find this helpful
