### ISSUE TITLE
requesting continuous integration badge for the confidence use of Viz.js

### ISSUE THREAD

**Issue by thari** [mdaines/viz.js#93]
Can you please use any of the free cloud-based continuous integration with Viz.js?
Including the badge will let us know the test cases that work with your build version.

Both Emscripten and Graphviz are evolving and I have seen when tools get updated they tend to break some test cases after transpiling using Emscripten.

**Comment by mdaines** [comment]
Addressed in 1b2d0ba32e163941fdd70302dea9f60e016f21b6 and 379e63d5e255762d5d1b3dfd787e057ac594f5f8
