### ISSUE TITLE
Assertion fails if rank=sink is used for a subgraph

### ISSUE THREAD

**Issue by sinopalnikov** [mdaines/viz.js#98]
The following example fails to get rendered on [viz-js.com](url):
`digraph test { A; B; { rank=sink; A } }`

I see the following error in the JS console:
`Assertion failed: !TREE_EDGE(e), at: ns.c,463,merge_trees at Error`

This is the stack trace:
```
invoke_v (viz.js:27)
LK (viz.js:35)
sL (viz.js:35)
Hi (viz.js:41)
Vf (viz.js:33)
Uf (viz.js:33)
Tf (viz.js:33)
uS (viz.js:36)
lG (viz.js:34)
Ib (viz.js:33)
ccallFunc (viz.js:27)
render (viz.js:87)
Viz (viz.js:75)
onmessage (worker.js:4)
```

The error is not reproducible if I change rank to 'min' or 'max', but it still fails with rank=source.
It does not fail if I remove node B.

I tried other websites that offer Graphviz rendering online and it fails the same way for 
https://dreampuf.github.io/GraphvizOnline/
but works on http://www.webgraphviz.com/ and https://stamm-wilbrandt.de/GraphvizFiddle/

**Comment by mdaines** [comment]
This appears to be a problem with Graphviz itself, or at least with version 2.40.1. I believe Webgraphviz uses an older version. When asking the `dot` command-line tool to render this graph, I get a segmentation fault. You may want to create a new issue on the [Graphviz issue tracker](https://gitlab.com/graphviz/graphviz/issues).

**Comment by sinopalnikov** [comment]
Thank you for the update!
Indeed `dot` crashes on this graph in version 2.40.1.
I also checked the latest dev snapshot, graphviz-2.41.20171026.1811, and it works fine.
So it seems the bug was fixed in Graphviz.
Do you have any plans to release a new version of viz.js based on Graphviz 2.41.x?
Thanks!

**Comment by mdaines** [comment]
Yes, I plan to update Viz.js for the next release version of Graphviz.

**Comment by joeltine** [comment]
@mdaines any idea when the new release will happen?

**Comment by mdaines** [comment]
@joeltine I don't know. I do follow Graphviz development, but if I miss the next stable release, feel free to open an issue here.
